import { Inter } from "next/font/google";
import { Navbar } from "./components/navbar";
import "./style/globals.css";
import "zenn-content-css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className=" min-h-screen overflow-clip">
          <Navbar />
          <div className=" w-hull h-full min-h-screen bg-[#e6e5e4]">
            <div className="md:mx-5 xl:max-w-[1120px] xl:mx-auto xl:px-0">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
